name: Deploying Image on Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Logging into Github Container Registry
        run: |
          echo $CR_PAT | docker login ghcr.io -u utkarsh-1905 --password-stdin
        env:
          CR_PAT: ${{ secrets.CR_PAT }}
      - name: Building Docker Image
        run: |
          docker build . -t ghcr.io/utkarsh-1905/docker-network-vis:${{ github.sha }}
      - name: Pushing Docker Image
        run: |
          docker push ghcr.io/utkarsh-1905/docker-network-vis:${{ github.sha }}
